language: ruby
rvm:
- 2.5.1
before_install:
- gem --version
- gem update --system 3.0.6
- gem --version
- bundler -v
- gem install bundler -v 2.0.2
- bundler -v
script: JEKYLL_ENV=production bundle exec jekyll build
after_success:
- openssl aes-256-cbc -K $encrypted_2a7123d3ade4_key -iv $encrypted_2a7123d3ade4_iv
  -in private_key.enc -out private_key -d
- chmod go-rwx private_key
- rsync -v -r -e "ssh -i private_key" _site/ $REMOTE_LOCATON
env:
  global:
    secure: SA68PKSrAoheK2UV+86ox6tGHXQrjcxscclBat3HzEY/8w0Yb9zxOO6mXzJim7wF/kjeJ8tdKrK9eVBudqcf6fTXp5DnTaJ/MBouD5RjyW2U+VFEr9yzGU33Zs+grN7DIDpiw/2Q2uWxRAI6OTrQZX6GOpG1CfMz4yGi6Fm26uJzDVFDWH3/chxc6Bmd0HyFnmLr+fw7pa5lysG11MVVz25RcGKmBmDOeE74KlKhHFw/+9gDINvFRVVzouuH3cK0nUfjJ2WHFHZ9TNxt1EVnU0P2oHogql7MJauXvvlUsS526m6ZWQMgJ/PXuNiKFcwmngwWdqc9WYAOS1a5NWnbm2gvoWJcQ/6YMv+xhEHFo8i7+moGae7T1m6FPf0ZM31Fmz1DUlSZ3eC6wItrvU9mcS6LSUxvd1M6CjqhHBZPxn9Q0ty+S7wo8V0mluHWsYC8hOADtd/DSmPkIlsx3a5vr/7tW6ryvydi9grYzcK1WiUH3N8MMRAowZ0CSMSHkS8TWXkCZMaKfO1zjtmErnN6pjGpdkxSP9P3KL5UxHcWys3RzAEP5FFRs3y/xDoSaYxlI3JqoxN/FZMCGV/EdLTecgg8R64zn2wwPIhwM7k7GizpOmmYOcVGwsJnGUN7CqbtGKSGQHK54is2PVl9KbIsERwHx2mH9voqNM2iZsK772Y=
addons:
  ssh_known_hosts: tinevanlent.be
