language: ruby
rvm:
- 2.5.1
before_install:
- gem --version
- gem update --system 3.0.6
- gem --version
- bundler -version
- gem install bundler -v 2.0.2
- bundler -v
script: JEKYLL_ENV=production bundle exec jekyll build
after_success:
- openssl aes-256-cbc -K $encrypted_2a7123d3ade4_key -iv $encrypted_2a7123d3ade4_iv
  -in private_key.enc -out private_key -d
- chmod go-rwx private_key
- rsync -v -r -e "ssh -i private_key" _site/ $REMOTE_USER@tinevanlent.be:$REMOTE_PATH
env:
  global:
  - secure: Y3uQ6ZrY76cyY7DsxIIJ2wI+dA8ZYreysH5FSoGx1m600rDz+xIJJL0Vq1BdX0ZbIJHiTFMDe5qLEFbxRLyXTSW6cGExpmJGUgZlxwz0di7RgPuq5vQDNiNSD1+PNnbcad9eTRwJo2lp/IlhjbCIskAH5hDkHFTvbbWUTA3ZPgRMDmWEMu7vvxH4c2EyerlW7K6ATD5f+ftt3Lp3xkAtO7br4691eF5j3/e64BLYx1VXirkFvN7jYJ059s32cfKOzGKkU8+PkjMhj8RtVl1KQHM8YI0xoW5z2Fpmh1TpL/K2rd9jFI6Lk3FIO4zwenCDHf64Ou1MSyi2A6IyOTwSFDwZiWrSv/hJvo/WkDhtqA+TZ+PTsdWVAlR8I2Z5wzZ31VW4XNGxJCOHRU9jjbsgUY8nkc7Unm5mOmLiwfRCte3uSM5oRSmoMbnRHDpH1kBDOPpYM7SpBqmtO9CG0X/4YxqirmPlY44yhHr0wF/+Lq6UZnXeLLxRdSU6dEW6McIp6WiF0208SW+/zT1dqTV+NbZ1SOFJQOowhiC0fmtxx/m9kWxNV+dBEhwWf7cP2VlVp34EQcf6BxIeK0te+SAGJ9+q/7gXryvjZGkXcXr1x9zdcugIVqRJP5k6zlnbsWhjKdhFRkxyfuW6kobpOnkrf5RckngpXeycHjG6UZDCsTM=
  - secure: OrbB1WrcmlQZ/G6yae+kPOd4ci2SJWH2XBceVSDVxXQHZaIT8h85PfgkGJKpGjIPIDsn3PzLmRCR6nja5EWnCPd6e2Qeq/YygtPv2nIGqcYdZsDKT2f7WrIk/SJuQ0trNAie2Gkltnd3TdLeE5EdkHoRaJ219ptVq3m/5DSZmoH7KBiCFHaFzz8ezOowKCNwTErXBHpY872SHu0eNhh+WUb3ppIUkSvj6QOstE1HHEMfOlpGW7plkX8eYZLjqxt8RQVAxL5nASTKb5ZwMw7UKldYaPPyPAae3JWWsjGG+MNxPYX7sDZkdYYg39pL6hRVd6YpIHVxTergIhzDLZhhLKkdooFlN09X2VI9odNmRI8ghMu0Stl4g35OGSipLPPPYyV34CRKHb9OpL2HvneH8/Rred3Lu2u57ym0iQ+zxI8/c+DpUoTm890hLp5BPOFty79vkO5yejsIJvRV4asaHiVt58I5X/Qg7t+ovyAqTp/jbQzSQd7oETWDWdcXLF+yEPD9JslRNVKT3DgNdmC+YhLmHgkZYHqAZd6EvUBEivz5zrka8oUkycGrenFFMzQ7qm3REJn+Qm0LlB50Du0nGlGVfVTWP2lHMsrb7IlVl3fmgTYbpXLaf5Ujvfz5bujmU0W32lzqxzMLhHKFDWk8Abi1j86Ya6FlLmdWQ5ui1Gs=
addons:
  ssh_known_hosts: tinevanlent.be
