version: '3.8'

services:
    # Run development Jekyll web server
    web:
        platform: linux/amd64
        build: .
        ports:
            - "4000:4000"
        command: "jekyll serve --host 0.0.0.0"
        volumes:
            - ".:/src"
