<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

{% for thumbnail in image_files %}<a href="{{ thumbnail.path  | replace: 'thumbnails', 'fullsize' | replace: 'png', 'jpg' | replace: 'gif', 'jpg' | uri_escape  | relative_url }}" style="display:inline" data-fancybox="gallery"><img src="{{ thumbnail.path | uri_escape  | relative_url }}" alt="*" width="100" height="100" style="display:inline" /></a>{% endfor %}
